#!/usr/bin/env php
<?php
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    define('ENV', 'DEV');
    require __DIR__ . '/vendor/autoload.php';
} else {
    define('ENV', 'PRO');
    require __DIR__ . '/../../autoload.php';
}
PhpPmd\Pmd\Pmd::run();

